from typing import List
import docking.widgets.table
import ghidra.app.plugin.core.debug.gui.thread
import java.lang
import java.util


class ThreadTableColumns(java.lang.Enum, docking.widgets.table.DefaultEnumeratedColumnTableModel.EnumeratedTableColumn):
    COMMENT: ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns = COMMENT
    CREATED: ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns = CREATED
    DESTROYED: ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns = DESTROYED
    NAME: ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns = NAME
    PLOT: ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns = PLOT
    STATE: ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns = STATE







    @overload
    def compareTo(self, __a0: java.lang.Enum) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def defaultSortDirection(self) -> docking.widgets.table.ColumnSortState.SortDirection: ...

    def describeConstable(self) -> java.util.Optional: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDeclaringClass(self) -> java.lang.Class: ...

    def getHeader(self) -> unicode: ...

    def getValueClass(self) -> java.lang.Class: ...

    @overload
    def getValueOf(self, __a0: ghidra.app.plugin.core.debug.gui.thread.ThreadRow) -> object: ...

    @overload
    def getValueOf(self, __a0: object) -> object: ...

    def hashCode(self) -> int: ...

    @overload
    def isEditable(self, __a0: ghidra.app.plugin.core.debug.gui.thread.ThreadRow) -> bool: ...

    @overload
    def isEditable(self, __a0: object) -> bool: ...

    def isSortable(self) -> bool: ...

    def name(self) -> unicode: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def ordinal(self) -> int: ...

    @overload
    def setValueOf(self, __a0: ghidra.app.plugin.core.debug.gui.thread.ThreadRow, __a1: object) -> None: ...

    @overload
    def setValueOf(self, __a0: object, __a1: object) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    @staticmethod
    def valueOf(__a0: unicode) -> ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns: ...

    @overload
    @staticmethod
    def valueOf(__a0: java.lang.Class, __a1: unicode) -> java.lang.Enum: ...

    @staticmethod
    def values() -> List[ghidra.app.plugin.core.debug.gui.thread.ThreadTableColumns]: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def header(self) -> unicode: ...

    @property
    def sortable(self) -> bool: ...

    @property
    def valueClass(self) -> java.lang.Class: ...