# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\x86\x054\x9a'
full_git_hash = '8605349a88b816b89dedfcee18cf29a56dfe669e'
git_branch = 'HEAD'
dirty = False
