
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-15T16:29:02-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b764e15950729baf12820086f9713c47414990d1",
 "version": "3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
