from typing import List
import com.google.common.collect
import ghidra.pcode.exec
import java.lang


class BytesPcodeExecutorStateSpace(object):




    def __init__(self, __a0: ghidra.program.model.lang.Language, __a1: ghidra.program.model.address.AddressSpace, __a2: object): ...



    def clear(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def lower(self, __a0: com.google.common.collect.Range) -> long: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def read(self, __a0: long, __a1: int, __a2: ghidra.pcode.exec.PcodeExecutorStatePiece.Reason) -> List[int]: ...

    def toString(self) -> unicode: ...

    def upper(self, __a0: com.google.common.collect.Range) -> long: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def write(self, __a0: long, __a1: List[int], __a2: int, __a3: int) -> None: ...

