
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-16T17:56:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "eeeabfd7b6aa6a8d331f157a81c4b770e870f616",
 "version": "2023.2.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
