
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-16T05:16:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1f08e7cc0fae20174500f3b221eaa0204e64b45",
 "version": "1.18.2.post0.dev88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
