"""
    MetaFab API

    Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.5.1
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metafab_python
from metafab_python.model.contract_model import ContractModel
from metafab_python.model.get_collections200_response_inner_all_of import GetCollections200ResponseInnerAllOf
from metafab_python.model.shop_model import ShopModel
globals()['ContractModel'] = ContractModel
globals()['GetCollections200ResponseInnerAllOf'] = GetCollections200ResponseInnerAllOf
globals()['ShopModel'] = ShopModel
from metafab_python.model.get_shops200_response_inner import GetShops200ResponseInner


class TestGetShops200ResponseInner(unittest.TestCase):
    """GetShops200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetShops200ResponseInner(self):
        """Test GetShops200ResponseInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetShops200ResponseInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
