"""
    MetaFab API

    Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.5.1
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metafab_python
from metafab_python.model.profile_permissions import ProfilePermissions
globals()['ProfilePermissions'] = ProfilePermissions
from metafab_python.model.update_profile_player_request import UpdateProfilePlayerRequest


class TestUpdateProfilePlayerRequest(unittest.TestCase):
    """UpdateProfilePlayerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateProfilePlayerRequest(self):
        """Test UpdateProfilePlayerRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateProfilePlayerRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
