"""
    MetaFab API

    Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.5.1
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metafab_python
from metafab_python.model.update_game200_response_all_of import UpdateGame200ResponseAllOf


class TestUpdateGame200ResponseAllOf(unittest.TestCase):
    """UpdateGame200ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateGame200ResponseAllOf(self):
        """Test UpdateGame200ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateGame200ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
