"""
    MetaFab API

    Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.5.1
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metafab_python
from metafab_python.model.public_player_custodial_wallet import PublicPlayerCustodialWallet


class TestPublicPlayerCustodialWallet(unittest.TestCase):
    """PublicPlayerCustodialWallet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicPlayerCustodialWallet(self):
        """Test PublicPlayerCustodialWallet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PublicPlayerCustodialWallet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
