"""
    MetaFab API

    Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.5.1
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import metafab_python
from metafab_python.model.grant_collection_role_request import GrantCollectionRoleRequest


class TestGrantCollectionRoleRequest(unittest.TestCase):
    """GrantCollectionRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantCollectionRoleRequest(self):
        """Test GrantCollectionRoleRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GrantCollectionRoleRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
