"""
    MetaFab API

    Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.5.1
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import metafab_python
from metafab_python.api.wallets_api import WalletsApi  # noqa: E501


class TestWalletsApi(unittest.TestCase):
    """WalletsApi unit test stubs"""

    def setUp(self):
        self.api = WalletsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_wallet_signature(self):
        """Test case for create_wallet_signature

        Create wallet signature  # noqa: E501
        """
        pass

    def test_get_wallet(self):
        """Test case for get_wallet

        Get wallet  # noqa: E501
        """
        pass

    def test_get_wallet_balances(self):
        """Test case for get_wallet_balances

        Get wallet balances  # noqa: E501
        """
        pass

    def test_get_wallet_transactions(self):
        """Test case for get_wallet_transactions

        Get wallet transactions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
