# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_temp.ipynb.

# %% auto 0
__all__ = ['add', 'name']

# %% ../nbs/01_temp.ipynb 3
def add(a,b):
    return a+b


# %% ../nbs/01_temp.ipynb 4
class name:
    def say_my_name(name1):
        return(name1)
    def first_letter(name1):
        return name1[0]
