
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-15T13:33:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "36b4219a1b538013a34286f6f68b32dab6f62cb8",
 "version": "2023.2.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
