"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class yun_info_t(object):
    __slots__ = ["utime", "ext_temp", "int_temp", "humidity", "leak", "flags"]

    __typenames__ = ["int64_t", "double", "double", "double", "int8_t", "int16_t"]

    __dimensions__ = [None, None, None, None, None, None]

    FLAG_NEW_MEASUREMENT = 1
    FLAG_OLD_MEASUREMENT = 0

    def __init__(self):
        self.utime = 0
        self.ext_temp = 0.0
        self.int_temp = 0.0
        self.humidity = 0.0
        self.leak = 0
        self.flags = 0

    def encode(self):
        buf = BytesIO()
        buf.write(yun_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddbh", self.utime, self.ext_temp, self.int_temp, self.humidity, self.leak, self.flags))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != yun_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return yun_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = yun_info_t()
        self.utime, self.ext_temp, self.int_temp, self.humidity, self.leak, self.flags = struct.unpack(">qdddbh", buf.read(35))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if yun_info_t in parents: return 0
        tmphash = (0xbe0da5e35212cd6d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if yun_info_t._packed_fingerprint is None:
            yun_info_t._packed_fingerprint = struct.pack(">Q", yun_info_t._get_hash_recursive([]))
        return yun_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", yun_info_t._get_packed_fingerprint())[0]

