from enum import Enum


class DirectdebitMessageResponseCode(str, Enum):
    GENERAL = "GENERAL"
    DUPLICATE = "DUPLICATE"
    MFADEVICEMM = "MFADEVICEMM"
    PERMISSION = "PERMISSION"
    MFAMESSAGEINVALID = "MFAMESSAGEINVALID"
    RATELIMIT = "RATELIMIT"
    MFASTATUS = "MFASTATUS"
    INVALID = "INVALID"
    NOTFOUND = "NOTFOUND"
    MFATIMEOUT = "MFATIMEOUT"
    MFAERROR = "MFAERROR"
    BUSINESSRULE = "BUSINESSRULE"
    RETRY = "RETRY"
    CONNECTION = "CONNECTION"

    def __str__(self) -> str:
        return str(self.value)
