"""add MatchReport.region column

Revision ID: 643ac9d51943
Revises: 77fff15ec613
Create Date: 2023-02-17 13:04:44.597439

"""  # noqa: W291
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "643ac9d51943"
down_revision = "77fff15ec613"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_report", sa.Column("region", sa.Unicode(), nullable=True))
    op.add_column("match_report_version", sa.Column("region", sa.Unicode(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_report_version", "region")
    op.drop_column("match_report", "region")
    # ### end Alembic commands ###
