# coding: utf-8

"""
    decentro-in-kyc

    KYC & Onboarding  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import decentro_in_kyc_client
from decentro_in_kyc_client.model.validate400_response import Validate400Response
from decentro_in_kyc_client import configuration


class TestValidate400Response(unittest.TestCase):
    """Validate400Response unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
