from typing import List
import ghidra.app.plugin.core.debug.mapping
import ghidra.app.plugin.core.debug.service.model.interfaces
import ghidra.dbg.target
import ghidra.program.model.address
import ghidra.util.datastruct
import java.lang
import java.util
import java.util.concurrent
import java.util.function


class RecorderComposedMemory(object, ghidra.app.plugin.core.debug.service.model.interfaces.AbstractRecorderMemory):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.service.model.interfaces.AbstractRecorderMemory): ...



    def addMemory(self, __a0: ghidra.dbg.target.TargetMemory) -> None: ...

    def addRegion(self, __a0: ghidra.dbg.target.TargetMemoryRegion, __a1: ghidra.dbg.target.TargetMemory) -> None: ...

    def alignAndLimitToFloor(self, __a0: ghidra.program.model.address.Address, __a1: int) -> ghidra.program.model.address.AddressRange: ...

    def alignWithOptionalLimit(self, __a0: ghidra.program.model.address.Address, __a1: int, __a2: ghidra.dbg.target.TargetMemoryRegion) -> ghidra.program.model.address.AddressRange: ...

    def equals(self, __a0: object) -> bool: ...

    def findChainedFloor(self, __a0: ghidra.program.model.address.Address) -> java.util.Map.Entry: ...

    def getAccessibleMemory(self, __a0: java.util.function.Predicate, __a1: ghidra.app.plugin.core.debug.mapping.DebuggerMemoryMapper) -> ghidra.program.model.address.AddressSet: ...

    def getClass(self) -> java.lang.Class: ...

    def getMemAccListeners(self) -> ghidra.util.datastruct.ListenerSet: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def readMemory(self, __a0: ghidra.program.model.address.Address, __a1: int) -> java.util.concurrent.CompletableFuture: ...

    def removeMemory(self, __a0: ghidra.dbg.target.TargetMemory) -> None: ...

    def removeRegion(self, __a0: ghidra.dbg.target.TargetObject) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeMemory(self, __a0: ghidra.program.model.address.Address, __a1: List[int]) -> java.util.concurrent.CompletableFuture: ...

    @property
    def memAccListeners(self) -> ghidra.util.datastruct.ListenerSet: ...