import ghidra.dbg.target
import java.lang
import java.util


class RecorderComposedRegisterSet(object):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.service.model.DefaultTraceRecorder): ...



    def checkRegistersRemoved(self, __a0: java.util.Map, __a1: ghidra.dbg.target.TargetObject) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isRegisterBankAccessible(self, __a0: ghidra.dbg.target.TargetRegisterBank) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    def updateRegisters(self, __a0: ghidra.dbg.target.TargetRegisterBank, __a1: ghidra.dbg.target.TargetRegisterBank) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

