
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-19T00:57:34+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fdeefd63dfd3e8e0272b30bc2d11ddc80156446",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
