VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('15')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('28')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202302151228
version_date = '2023/02/15 12:28'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
