"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_ocr_text_request import GetOcrTextRequest


class TestGetOcrTextRequest(unittest.TestCase):
    """GetOcrTextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOcrTextRequest(self):
        """Test GetOcrTextRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetOcrTextRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
