"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_ocr_text_response_entity import GetOcrTextResponseEntity
globals()['GetOcrTextResponseEntity'] = GetOcrTextResponseEntity
from dojah_client.model.get_ocr_text_response import GetOcrTextResponse


class TestGetOcrTextResponse(unittest.TestCase):
    """GetOcrTextResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOcrTextResponse(self):
        """Test GetOcrTextResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetOcrTextResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
