"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.notify_webhook_response import NotifyWebhookResponse


class TestNotifyWebhookResponse(unittest.TestCase):
    """NotifyWebhookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotifyWebhookResponse(self):
        """Test NotifyWebhookResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotifyWebhookResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
