"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_account_transactions_response_entity_transactions_inner import GetAccountTransactionsResponseEntityTransactionsInner
globals()['GetAccountTransactionsResponseEntityTransactionsInner'] = GetAccountTransactionsResponseEntityTransactionsInner
from dojah_client.model.get_account_transactions_response_entity import GetAccountTransactionsResponseEntity


class TestGetAccountTransactionsResponseEntity(unittest.TestCase):
    """GetAccountTransactionsResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccountTransactionsResponseEntity(self):
        """Test GetAccountTransactionsResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAccountTransactionsResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
