"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.verify_age_response_entity import VerifyAgeResponseEntity
globals()['VerifyAgeResponseEntity'] = VerifyAgeResponseEntity
from dojah_client.model.verify_age_response import VerifyAgeResponse


class TestVerifyAgeResponse(unittest.TestCase):
    """VerifyAgeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyAgeResponse(self):
        """Test VerifyAgeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VerifyAgeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
