"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.verify_photo_id_with_selfie_response_entity import VerifyPhotoIdWithSelfieResponseEntity
globals()['VerifyPhotoIdWithSelfieResponseEntity'] = VerifyPhotoIdWithSelfieResponseEntity
from dojah_client.model.verify_photo_id_with_selfie_response import VerifyPhotoIdWithSelfieResponse


class TestVerifyPhotoIdWithSelfieResponse(unittest.TestCase):
    """VerifyPhotoIdWithSelfieResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyPhotoIdWithSelfieResponse(self):
        """Test VerifyPhotoIdWithSelfieResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VerifyPhotoIdWithSelfieResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
