"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.verify_selfie_nin_response_entity_selfie_verification import VerifySelfieNinResponseEntitySelfieVerification


class TestVerifySelfieNinResponseEntitySelfieVerification(unittest.TestCase):
    """VerifySelfieNinResponseEntitySelfieVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifySelfieNinResponseEntitySelfieVerification(self):
        """Test VerifySelfieNinResponseEntitySelfieVerification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VerifySelfieNinResponseEntitySelfieVerification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
