"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.verify_age_response_entity import VerifyAgeResponseEntity


class TestVerifyAgeResponseEntity(unittest.TestCase):
    """VerifyAgeResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyAgeResponseEntity(self):
        """Test VerifyAgeResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VerifyAgeResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
