"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_email_reputation_response_entity_details import GetEmailReputationResponseEntityDetails
globals()['GetEmailReputationResponseEntityDetails'] = GetEmailReputationResponseEntityDetails
from dojah_client.model.get_email_reputation_response_entity import GetEmailReputationResponseEntity


class TestGetEmailReputationResponseEntity(unittest.TestCase):
    """GetEmailReputationResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEmailReputationResponseEntity(self):
        """Test GetEmailReputationResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEmailReputationResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
