"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_transaction_response_entity import GetTransactionResponseEntity
globals()['GetTransactionResponseEntity'] = GetTransactionResponseEntity
from dojah_client.model.get_transaction_response import GetTransactionResponse


class TestGetTransactionResponse(unittest.TestCase):
    """GetTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransactionResponse(self):
        """Test GetTransactionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTransactionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
