"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_premium_bvn_response_entity import GetPremiumBvnResponseEntity


class TestGetPremiumBvnResponseEntity(unittest.TestCase):
    """GetPremiumBvnResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPremiumBvnResponseEntity(self):
        """Test GetPremiumBvnResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPremiumBvnResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
