"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_spending_pattern_response_entity_pattern_others import GetSpendingPatternResponseEntityPatternOthers


class TestGetSpendingPatternResponseEntityPatternOthers(unittest.TestCase):
    """GetSpendingPatternResponseEntityPatternOthers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSpendingPatternResponseEntityPatternOthers(self):
        """Test GetSpendingPatternResponseEntityPatternOthers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSpendingPatternResponseEntityPatternOthers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
