"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.get_sms_status_response_entity import GetSmsStatusResponseEntity
globals()['GetSmsStatusResponseEntity'] = GetSmsStatusResponseEntity
from dojah_client.model.get_sms_status_response import GetSmsStatusResponse


class TestGetSmsStatusResponse(unittest.TestCase):
    """GetSmsStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSmsStatusResponse(self):
        """Test GetSmsStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSmsStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
