"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import dojah_client
from dojah_client.model.send_sms_request import SendSmsRequest


class TestSendSmsRequest(unittest.TestCase):
    """SendSmsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendSmsRequest(self):
        """Test SendSmsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendSmsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
