
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-15T05:24:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1099e4aed379c44ab4711f00f91684da7d8443cf",
 "version": "1.18.2.post0.dev86"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
