"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cmd_list_t(object):
    __slots__ = ["utime", "len", "commands"]

    __typenames__ = ["int64_t", "int32_t", "double"]

    __dimensions__ = [None, None, ["len"]]

    def __init__(self):
        self.utime = 0
        self.len = 0
        self.commands = []

    def encode(self):
        buf = BytesIO()
        buf.write(cmd_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.len))
        buf.write(struct.pack('>%dd' % self.len, *self.commands[:self.len]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cmd_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cmd_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cmd_list_t()
        self.utime, self.len = struct.unpack(">qi", buf.read(12))
        self.commands = struct.unpack('>%dd' % self.len, buf.read(self.len * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if cmd_list_t in parents: return 0
        tmphash = (0xa04d56805e537ee1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cmd_list_t._packed_fingerprint is None:
            cmd_list_t._packed_fingerprint = struct.pack(">Q", cmd_list_t._get_hash_recursive([]))
        return cmd_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cmd_list_t._get_packed_fingerprint())[0]

