depends = ('ITKPyBase', 'ITKThresholding', 'ITKSmoothing', 'ITKMesh', 'ITKImageIntensity', 'ITKImageFilterBase', 'ITKDistanceMap', 'ITKCommon', )
templates = (  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterISS3MSS3', True, 'itk::Image< signed short,3 >, itk::Mesh< signed short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterISS3MUC3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned char,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterISS3MUS3', True, 'itk::Image< signed short,3 >, itk::Mesh< unsigned short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterISS3MF3', True, 'itk::Image< signed short,3 >, itk::Mesh< float,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterISS3MD3', True, 'itk::Image< signed short,3 >, itk::Mesh< double,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUC3MSS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< signed short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUC3MUC3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned char,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUC3MUS3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< unsigned short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUC3MF3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< float,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUC3MD3', True, 'itk::Image< unsigned char,3 >, itk::Mesh< double,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUS3MSS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< signed short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUS3MUC3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned char,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUS3MUS3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< unsigned short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUS3MF3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< float,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIUS3MD3', True, 'itk::Image< unsigned short,3 >, itk::Mesh< double,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIF3MSS3', True, 'itk::Image< float,3 >, itk::Mesh< signed short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIF3MUC3', True, 'itk::Image< float,3 >, itk::Mesh< unsigned char,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIF3MUS3', True, 'itk::Image< float,3 >, itk::Mesh< unsigned short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIF3MF3', True, 'itk::Image< float,3 >, itk::Mesh< float,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterIF3MD3', True, 'itk::Image< float,3 >, itk::Mesh< double,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterID3MSS3', True, 'itk::Image< double,3 >, itk::Mesh< signed short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterID3MUC3', True, 'itk::Image< double,3 >, itk::Mesh< unsigned char,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterID3MUS3', True, 'itk::Image< double,3 >, itk::Mesh< unsigned short,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterID3MF3', True, 'itk::Image< double,3 >, itk::Mesh< float,3 >'),
  ('CleaverImageToMeshFilter', 'itk::CleaverImageToMeshFilter', 'itkCleaverImageToMeshFilterID3MD3', True, 'itk::Image< double,3 >, itk::Mesh< double,3 >'),
)
factories = ()
