
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-17T15:44:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e8258a0204966135d23c04a009737f437ca76b4",
 "version": "6.15.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
