from enum import Enum


class NotificationNotificationResponseType(str, Enum):
    UPCOMING_CREDIT = "UPCOMING_CREDIT"
    DDMANDATE = "DDMANDATE"
    PENDING_PAYMENTS = "PENDING_PAYMENTS"
    CARD_AUTH = "CARD_AUTH"
    PAYMENT_FILE_UPLOAD = "PAYMENT_FILE_UPLOAD"
    PAYIN = "PAYIN"
    CUSTVSTAT = "CUSTVSTAT"
    UPCOMING_COLLECTION_DEBIT = "UPCOMING_COLLECTION_DEBIT"
    PAYOUT = "PAYOUT"
    ACCOUNT_SWITCH_UPDATE = "ACCOUNT_SWITCH_UPDATE"
    BALANCE_LOW = "BALANCE_LOW"
    CARD_CREATION = "CARD_CREATION"
    CARD_TOKEN_PROVISIONING = "CARD_TOKEN_PROVISIONING"
    BALANCE = "BALANCE"
    BALANCE_HIGH = "BALANCE_HIGH"
    DD_COLLECTION_STATUS = "DD_COLLECTION_STATUS"
    DD_FAILED_CLAIM = "DD_FAILED_CLAIM"
    PAYMENT_COMPLIANCE_STATUS = "PAYMENT_COMPLIANCE_STATUS"
    DD_INCOMING_DEBIT = "DD_INCOMING_DEBIT"
    ACCOUNT_STATEMENT = "ACCOUNT_STATEMENT"
    CARD_STATUS_UPDATE = "CARD_STATUS_UPDATE"
    UPCOMING_COLLECTION_CREDIT = "UPCOMING_COLLECTION_CREDIT"
    DD_FUNDS_RETURNED = "DD_FUNDS_RETURNED"

    def __str__(self) -> str:
        return str(self.value)
