from enum import Enum


class PaymentStatusItem(str, Enum):
    HELD = "HELD"
    RETURNED = "RETURNED"
    ER_EXTCONN = "ER_EXTCONN"
    ER_EXPIRED = "ER_EXPIRED"
    CANCELLED = "CANCELLED"
    RECONCILED = "RECONCILED"
    CLEARING = "CLEARING"
    EXT_PROC = "EXT_PROC"
    ER_BATCH = "ER_BATCH"
    ER_EXTSYS = "ER_EXTSYS"
    SUBMITTED = "SUBMITTED"
    SCREENING_REQ = "SCREENING_REQ"
    VALIDATED = "VALIDATED"
    REPROCESSING = "REPROCESSING"
    VOID = "VOID"
    PROCESSED = "PROCESSED"
    UNALLOCATED = "UNALLOCATED"
    ER_GENERAL = "ER_GENERAL"
    ER_INVALID = "ER_INVALID"
    PENDING_FOR_FUNDS = "PENDING_FOR_FUNDS"
    PENDING_FOR_DATE = "PENDING_FOR_DATE"
    EXT_SENT = "EXT_SENT"

    def __str__(self) -> str:
        return str(self.value)
