
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-15T08:35:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "81ee991c33c82d98287638e0d63f0c1a1b6815b8",
 "version": "0.1.0a85"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
