
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-17T13:56:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7827b3fdd95f1af0e05eded2f79aee8fed0d0da7",
 "version": "0.15.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
