# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/geometry/v0/coordinatesystems.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ansys/api/geometry/v0/coordinatesystems.proto',
  package='ansys.api.geometry.v0.CoordinateSystems',
  syntax='proto3',
  serialized_options=_b('\252\002\'Ansys.Api.Geometry.V0.CoordinateSystems'),
  serialized_pb=_b('\n-ansys/api/geometry/v0/coordinatesystems.proto\x12\'ansys.api.geometry.v0.CoordinateSystems\x1a\"ansys/api/geometry/v0/models.proto\"\x1f\n\rGetAllRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\"U\n\x0eGetAllResponse\x12\x43\n\x12\x63oordinate_systems\x18\x01 \x03(\x0b\x32\'.ansys.api.geometry.v0.CoordinateSystem\"Z\n\rCreateRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12+\n\x05\x66rame\x18\x03 \x01(\x0b\x32\x1c.ansys.api.geometry.v0.Frame\"T\n\x0e\x43reateResponse\x12\x42\n\x11\x63oordinate_system\x18\x01 \x01(\x0b\x32\'.ansys.api.geometry.v0.CoordinateSystem2\xd2\x02\n\x11\x43oordinateSystems\x12W\n\x03Get\x12\'.ansys.api.geometry.v0.EntityIdentifier\x1a\'.ansys.api.geometry.v0.CoordinateSystem\x12y\n\x06GetAll\x12\x36.ansys.api.geometry.v0.CoordinateSystems.GetAllRequest\x1a\x37.ansys.api.geometry.v0.CoordinateSystems.GetAllResponse\x12i\n\x06\x43reate\x12\x36.ansys.api.geometry.v0.CoordinateSystems.CreateRequest\x1a\'.ansys.api.geometry.v0.CoordinateSystemB*\xaa\x02\'Ansys.Api.Geometry.V0.CoordinateSystemsb\x06proto3')
  ,
  dependencies=[ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.DESCRIPTOR,])




_GETALLREQUEST = _descriptor.Descriptor(
  name='GetAllRequest',
  full_name='ansys.api.geometry.v0.CoordinateSystems.GetAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='ansys.api.geometry.v0.CoordinateSystems.GetAllRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=157,
)


_GETALLRESPONSE = _descriptor.Descriptor(
  name='GetAllResponse',
  full_name='ansys.api.geometry.v0.CoordinateSystems.GetAllResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate_systems', full_name='ansys.api.geometry.v0.CoordinateSystems.GetAllResponse.coordinate_systems', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=244,
)


_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='ansys.api.geometry.v0.CoordinateSystems.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='ansys.api.geometry.v0.CoordinateSystems.CreateRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ansys.api.geometry.v0.CoordinateSystems.CreateRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='ansys.api.geometry.v0.CoordinateSystems.CreateRequest.frame', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=336,
)


_CREATERESPONSE = _descriptor.Descriptor(
  name='CreateResponse',
  full_name='ansys.api.geometry.v0.CoordinateSystems.CreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinate_system', full_name='ansys.api.geometry.v0.CoordinateSystems.CreateResponse.coordinate_system', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=422,
)

_GETALLRESPONSE.fields_by_name['coordinate_systems'].message_type = ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._COORDINATESYSTEM
_CREATEREQUEST.fields_by_name['frame'].message_type = ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._FRAME
_CREATERESPONSE.fields_by_name['coordinate_system'].message_type = ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._COORDINATESYSTEM
DESCRIPTOR.message_types_by_name['GetAllRequest'] = _GETALLREQUEST
DESCRIPTOR.message_types_by_name['GetAllResponse'] = _GETALLRESPONSE
DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['CreateResponse'] = _CREATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLREQUEST,
  __module__ = 'ansys.api.geometry.v0.coordinatesystems_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.CoordinateSystems.GetAllRequest)
  ))
_sym_db.RegisterMessage(GetAllRequest)

GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETALLRESPONSE,
  __module__ = 'ansys.api.geometry.v0.coordinatesystems_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.CoordinateSystems.GetAllResponse)
  ))
_sym_db.RegisterMessage(GetAllResponse)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEREQUEST,
  __module__ = 'ansys.api.geometry.v0.coordinatesystems_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.CoordinateSystems.CreateRequest)
  ))
_sym_db.RegisterMessage(CreateRequest)

CreateResponse = _reflection.GeneratedProtocolMessageType('CreateResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATERESPONSE,
  __module__ = 'ansys.api.geometry.v0.coordinatesystems_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.CoordinateSystems.CreateResponse)
  ))
_sym_db.RegisterMessage(CreateResponse)


DESCRIPTOR._options = None

_COORDINATESYSTEMS = _descriptor.ServiceDescriptor(
  name='CoordinateSystems',
  full_name='ansys.api.geometry.v0.CoordinateSystems.CoordinateSystems',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=425,
  serialized_end=763,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='ansys.api.geometry.v0.CoordinateSystems.CoordinateSystems.Get',
    index=0,
    containing_service=None,
    input_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._ENTITYIDENTIFIER,
    output_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._COORDINATESYSTEM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='ansys.api.geometry.v0.CoordinateSystems.CoordinateSystems.GetAll',
    index=1,
    containing_service=None,
    input_type=_GETALLREQUEST,
    output_type=_GETALLRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='ansys.api.geometry.v0.CoordinateSystems.CoordinateSystems.Create',
    index=2,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._COORDINATESYSTEM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATESYSTEMS)

DESCRIPTOR.services_by_name['CoordinateSystems'] = _COORDINATESYSTEMS

# @@protoc_insertion_point(module_scope)
