# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/geometry/v0/edges.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ansys/api/geometry/v0/edges.proto',
  package='ansys.api.geometry.v0.Edges',
  syntax='proto3',
  serialized_options=_b('\252\002\033Ansys.Api.Geometry.V0.Edges'),
  serialized_pb=_b('\n!ansys/api/geometry/v0/edges.proto\x12\x1b\x61nsys.api.geometry.v0.Edges\x1a\"ansys/api/geometry/v0/models.proto\"\x1f\n\rGetAllRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\"<\n\x0eGetAllResponse\x12*\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x1b.ansys.api.geometry.v0.Edge\">\n\x10GetFacesResponse\x12*\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x1b.ansys.api.geometry.v0.Face\"$\n\x11IsDeletedResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"#\n\x11GetLengthResponse\x12\x0e\n\x06length\x18\x01 \x01(\x01\x32\xe7\x03\n\x05\x45\x64ges\x12K\n\x03Get\x12\'.ansys.api.geometry.v0.EntityIdentifier\x1a\x1b.ansys.api.geometry.v0.Edge\x12\x61\n\x06GetAll\x12*.ansys.api.geometry.v0.Edges.GetAllRequest\x1a+.ansys.api.geometry.v0.Edges.GetAllResponse\x12\x62\n\x08GetFaces\x12\'.ansys.api.geometry.v0.EntityIdentifier\x1a-.ansys.api.geometry.v0.Edges.GetFacesResponse\x12\x64\n\tGetLength\x12\'.ansys.api.geometry.v0.EntityIdentifier\x1a..ansys.api.geometry.v0.Edges.GetLengthResponse\x12\x64\n\tIsDeleted\x12\'.ansys.api.geometry.v0.EntityIdentifier\x1a..ansys.api.geometry.v0.Edges.IsDeletedResponseB\x1e\xaa\x02\x1b\x41nsys.Api.Geometry.V0.Edgesb\x06proto3')
  ,
  dependencies=[ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.DESCRIPTOR,])




_GETALLREQUEST = _descriptor.Descriptor(
  name='GetAllRequest',
  full_name='ansys.api.geometry.v0.Edges.GetAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='ansys.api.geometry.v0.Edges.GetAllRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=133,
)


_GETALLRESPONSE = _descriptor.Descriptor(
  name='GetAllResponse',
  full_name='ansys.api.geometry.v0.Edges.GetAllResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edges', full_name='ansys.api.geometry.v0.Edges.GetAllResponse.edges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=195,
)


_GETFACESRESPONSE = _descriptor.Descriptor(
  name='GetFacesResponse',
  full_name='ansys.api.geometry.v0.Edges.GetFacesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faces', full_name='ansys.api.geometry.v0.Edges.GetFacesResponse.faces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=259,
)


_ISDELETEDRESPONSE = _descriptor.Descriptor(
  name='IsDeletedResponse',
  full_name='ansys.api.geometry.v0.Edges.IsDeletedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='ansys.api.geometry.v0.Edges.IsDeletedResponse.deleted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=297,
)


_GETLENGTHRESPONSE = _descriptor.Descriptor(
  name='GetLengthResponse',
  full_name='ansys.api.geometry.v0.Edges.GetLengthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='ansys.api.geometry.v0.Edges.GetLengthResponse.length', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=334,
)

_GETALLRESPONSE.fields_by_name['edges'].message_type = ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._EDGE
_GETFACESRESPONSE.fields_by_name['faces'].message_type = ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._FACE
DESCRIPTOR.message_types_by_name['GetAllRequest'] = _GETALLREQUEST
DESCRIPTOR.message_types_by_name['GetAllResponse'] = _GETALLRESPONSE
DESCRIPTOR.message_types_by_name['GetFacesResponse'] = _GETFACESRESPONSE
DESCRIPTOR.message_types_by_name['IsDeletedResponse'] = _ISDELETEDRESPONSE
DESCRIPTOR.message_types_by_name['GetLengthResponse'] = _GETLENGTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETALLREQUEST,
  __module__ = 'ansys.api.geometry.v0.edges_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Edges.GetAllRequest)
  ))
_sym_db.RegisterMessage(GetAllRequest)

GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETALLRESPONSE,
  __module__ = 'ansys.api.geometry.v0.edges_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Edges.GetAllResponse)
  ))
_sym_db.RegisterMessage(GetAllResponse)

GetFacesResponse = _reflection.GeneratedProtocolMessageType('GetFacesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETFACESRESPONSE,
  __module__ = 'ansys.api.geometry.v0.edges_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Edges.GetFacesResponse)
  ))
_sym_db.RegisterMessage(GetFacesResponse)

IsDeletedResponse = _reflection.GeneratedProtocolMessageType('IsDeletedResponse', (_message.Message,), dict(
  DESCRIPTOR = _ISDELETEDRESPONSE,
  __module__ = 'ansys.api.geometry.v0.edges_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Edges.IsDeletedResponse)
  ))
_sym_db.RegisterMessage(IsDeletedResponse)

GetLengthResponse = _reflection.GeneratedProtocolMessageType('GetLengthResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETLENGTHRESPONSE,
  __module__ = 'ansys.api.geometry.v0.edges_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.Edges.GetLengthResponse)
  ))
_sym_db.RegisterMessage(GetLengthResponse)


DESCRIPTOR._options = None

_EDGES = _descriptor.ServiceDescriptor(
  name='Edges',
  full_name='ansys.api.geometry.v0.Edges.Edges',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=337,
  serialized_end=824,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='ansys.api.geometry.v0.Edges.Edges.Get',
    index=0,
    containing_service=None,
    input_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._ENTITYIDENTIFIER,
    output_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._EDGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='ansys.api.geometry.v0.Edges.Edges.GetAll',
    index=1,
    containing_service=None,
    input_type=_GETALLREQUEST,
    output_type=_GETALLRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFaces',
    full_name='ansys.api.geometry.v0.Edges.Edges.GetFaces',
    index=2,
    containing_service=None,
    input_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._ENTITYIDENTIFIER,
    output_type=_GETFACESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLength',
    full_name='ansys.api.geometry.v0.Edges.Edges.GetLength',
    index=3,
    containing_service=None,
    input_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._ENTITYIDENTIFIER,
    output_type=_GETLENGTHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IsDeleted',
    full_name='ansys.api.geometry.v0.Edges.Edges.IsDeleted',
    index=4,
    containing_service=None,
    input_type=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2._ENTITYIDENTIFIER,
    output_type=_ISDELETEDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDGES)

DESCRIPTOR.services_by_name['Edges'] = _EDGES

# @@protoc_insertion_point(module_scope)
