# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/geometry/v0/geometryapplication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ansys/api/geometry/v0/geometryapplication.proto',
  package='ansys.api.geometry.v0.GeometryApplication',
  syntax='proto3',
  serialized_options=_b('Z\025ansys/api/geometry/v0\252\002)Ansys.Api.Geometry.V0.GeometryApplication'),
  serialized_pb=_b('\n/ansys/api/geometry/v0/geometryapplication.proto\x12)ansys.api.geometry.v0.GeometryApplication\"\xd9\x01\n\x14RunScriptFileRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\x12\x64\n\x0bscript_args\x18\x02 \x03(\x0b\x32O.ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.ScriptArgsEntry\x12\x13\n\x0b\x61pi_version\x18\x03 \x01(\x05\x1a\x31\n\x0fScriptArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x15RunScriptFileResponse\x12\x1b\n\x13run_script_response\x18\x01 \x01(\t2\xaa\x01\n\x13GeometryApplication\x12\x92\x01\n\rRunScriptFile\x12?.ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest\x1a@.ansys.api.geometry.v0.GeometryApplication.RunScriptFileResponseBCZ\x15\x61nsys/api/geometry/v0\xaa\x02)Ansys.Api.Geometry.V0.GeometryApplicationb\x06proto3')
)




_RUNSCRIPTFILEREQUEST_SCRIPTARGSENTRY = _descriptor.Descriptor(
  name='ScriptArgsEntry',
  full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.ScriptArgsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.ScriptArgsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.ScriptArgsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=312,
)

_RUNSCRIPTFILEREQUEST = _descriptor.Descriptor(
  name='RunScriptFileRequest',
  full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='script_path', full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.script_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_args', full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.script_args', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.api_version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RUNSCRIPTFILEREQUEST_SCRIPTARGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=312,
)


_RUNSCRIPTFILERESPONSE = _descriptor.Descriptor(
  name='RunScriptFileResponse',
  full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_script_response', full_name='ansys.api.geometry.v0.GeometryApplication.RunScriptFileResponse.run_script_response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=366,
)

_RUNSCRIPTFILEREQUEST_SCRIPTARGSENTRY.containing_type = _RUNSCRIPTFILEREQUEST
_RUNSCRIPTFILEREQUEST.fields_by_name['script_args'].message_type = _RUNSCRIPTFILEREQUEST_SCRIPTARGSENTRY
DESCRIPTOR.message_types_by_name['RunScriptFileRequest'] = _RUNSCRIPTFILEREQUEST
DESCRIPTOR.message_types_by_name['RunScriptFileResponse'] = _RUNSCRIPTFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunScriptFileRequest = _reflection.GeneratedProtocolMessageType('RunScriptFileRequest', (_message.Message,), dict(

  ScriptArgsEntry = _reflection.GeneratedProtocolMessageType('ScriptArgsEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUNSCRIPTFILEREQUEST_SCRIPTARGSENTRY,
    __module__ = 'ansys.api.geometry.v0.geometryapplication_pb2'
    # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest.ScriptArgsEntry)
    ))
  ,
  DESCRIPTOR = _RUNSCRIPTFILEREQUEST,
  __module__ = 'ansys.api.geometry.v0.geometryapplication_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.GeometryApplication.RunScriptFileRequest)
  ))
_sym_db.RegisterMessage(RunScriptFileRequest)
_sym_db.RegisterMessage(RunScriptFileRequest.ScriptArgsEntry)

RunScriptFileResponse = _reflection.GeneratedProtocolMessageType('RunScriptFileResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNSCRIPTFILERESPONSE,
  __module__ = 'ansys.api.geometry.v0.geometryapplication_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.geometry.v0.GeometryApplication.RunScriptFileResponse)
  ))
_sym_db.RegisterMessage(RunScriptFileResponse)


DESCRIPTOR._options = None
_RUNSCRIPTFILEREQUEST_SCRIPTARGSENTRY._options = None

_GEOMETRYAPPLICATION = _descriptor.ServiceDescriptor(
  name='GeometryApplication',
  full_name='ansys.api.geometry.v0.GeometryApplication.GeometryApplication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=369,
  serialized_end=539,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunScriptFile',
    full_name='ansys.api.geometry.v0.GeometryApplication.GeometryApplication.RunScriptFile',
    index=0,
    containing_service=None,
    input_type=_RUNSCRIPTFILEREQUEST,
    output_type=_RUNSCRIPTFILERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GEOMETRYAPPLICATION)

DESCRIPTOR.services_by_name['GeometryApplication'] = _GEOMETRYAPPLICATION

# @@protoc_insertion_point(module_scope)
