# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ansys.api.geometry.v0 import models_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2
from ansys.api.geometry.v0 import parts_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2
from ansys.api.geometry.v0 import streaming_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_streaming__pb2


class PartsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/ansys.api.geometry.v0.Parts/Get',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.EntityIdentifier.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Part.FromString,
        )
    self.GetAll = channel.unary_unary(
        '/ansys.api.geometry.v0.Parts/GetAll',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2.GetAllRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2.GetAllResponse.FromString,
        )
    self.Export = channel.unary_stream(
        '/ansys.api.geometry.v0.Parts/Export',
        request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2.ExportRequest.SerializeToString,
        response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_streaming__pb2.StreamPackage.FromString,
        )


class PartsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Export(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PartsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.EntityIdentifier.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_models__pb2.Part.SerializeToString,
      ),
      'GetAll': grpc.unary_unary_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2.GetAllRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2.GetAllResponse.SerializeToString,
      ),
      'Export': grpc.unary_stream_rpc_method_handler(
          servicer.Export,
          request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_parts__pb2.ExportRequest.FromString,
          response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_streaming__pb2.StreamPackage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ansys.api.geometry.v0.Parts', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
