
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-17T14:20:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9602053c7ed2aaeb36e585bcae8c43e6d77c0d4",
 "version": "2023.02.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
