
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-14T16:32:41-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd884a7ef40f76f862449405d430fcc41cd10887",
 "version": "v0.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
