
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-19T02:29:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "04158ce219f6700e64044b56d24bba7db00557bd",
 "version": "1.2.dev2308"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
