
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-15T11:53:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "325f1b137c862c6483d8d4e72261e8fa7566cb14",
 "version": "0.9.92"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
