# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aus/proto/orchestration/data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aus.proto.orchestration import message_pb2 as aus_dot_proto_dot_orchestration_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aus/proto/orchestration/data.proto',
  package='aus.orchestration',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"aus/proto/orchestration/data.proto\x12\x11\x61us.orchestration\x1a%aus/proto/orchestration/message.proto\";\n\x07\x45xample\x12\x30\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\x1e.aus.orchestration.AusFeatures\"}\n\x0fSequenceExample\x12/\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1e.aus.orchestration.AusFeatures\x12\x39\n\rfeature_lists\x18\x02 \x01(\x0b\x32\".aus.orchestration.AusFeatureListsb\x06proto3')
  ,
  dependencies=[aus_dot_proto_dot_orchestration_dot_message__pb2.DESCRIPTOR,])




_EXAMPLE = _descriptor.Descriptor(
  name='Example',
  full_name='aus.orchestration.Example',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='aus.orchestration.Example.features', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=155,
)


_SEQUENCEEXAMPLE = _descriptor.Descriptor(
  name='SequenceExample',
  full_name='aus.orchestration.SequenceExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='aus.orchestration.SequenceExample.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_lists', full_name='aus.orchestration.SequenceExample.feature_lists', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=282,
)

_EXAMPLE.fields_by_name['features'].message_type = aus_dot_proto_dot_orchestration_dot_message__pb2._AUSFEATURES
_SEQUENCEEXAMPLE.fields_by_name['context'].message_type = aus_dot_proto_dot_orchestration_dot_message__pb2._AUSFEATURES
_SEQUENCEEXAMPLE.fields_by_name['feature_lists'].message_type = aus_dot_proto_dot_orchestration_dot_message__pb2._AUSFEATURELISTS
DESCRIPTOR.message_types_by_name['Example'] = _EXAMPLE
DESCRIPTOR.message_types_by_name['SequenceExample'] = _SEQUENCEEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Example = _reflection.GeneratedProtocolMessageType('Example', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLE,
  '__module__' : 'aus.proto.orchestration.data_pb2'
  # @@protoc_insertion_point(class_scope:aus.orchestration.Example)
  })
_sym_db.RegisterMessage(Example)

SequenceExample = _reflection.GeneratedProtocolMessageType('SequenceExample', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCEEXAMPLE,
  '__module__' : 'aus.proto.orchestration.data_pb2'
  # @@protoc_insertion_point(class_scope:aus.orchestration.SequenceExample)
  })
_sym_db.RegisterMessage(SequenceExample)


# @@protoc_insertion_point(module_scope)
